//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalsViewer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InternalsViewer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap allocationWindowSplit {
            get {
                object obj = ResourceManager.GetObject("allocationWindowSplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap allocationWindowSplit1 {
            get {
                object obj = ResourceManager.GetObject("allocationWindowSplit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bufferpool {
            get {
                object obj = ResourceManager.GetObject("bufferpool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Collapse_large {
            get {
                object obj = ResourceManager.GetObject("Collapse_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftToRightDoucmentHS1 {
            get {
                object obj = ResourceManager.GetObject("LeftToRightDoucmentHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pfs {
            get {
                object obj = ResourceManager.GetObject("pfs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightToLeftDoucmentHS {
            get {
                object obj = ResourceManager.GetObject("RightToLeftDoucmentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{\cf{0}\highlight{1} .
        /// </summary>
        internal static string Rtf_ColourHighlightTag {
            get {
                return ResourceManager.GetString("Rtf_ColourHighlightTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \red{0}\green{1}\blue{2};.
        /// </summary>
        internal static string Rtf_ColourTable {
            get {
                return ResourceManager.GetString("Rtf_ColourTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{\cf{0} .
        /// </summary>
        internal static string Rtf_ColourTag {
            get {
                return ResourceManager.GetString("Rtf_ColourTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}\viewkind4\uc1\pard\f0\fs17.
        /// </summary>
        internal static string Rtf_HeaderEnd {
            get {
                return ResourceManager.GetString("Rtf_HeaderEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Courier New;}{\colortbl;.
        /// </summary>
        internal static string Rtf_HeaderStart {
            get {
                return ResourceManager.GetString("Rtf_HeaderStart", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap showhidedetailstoolbarbutton {
            get {
                object obj = ResourceManager.GetObject("showhidedetailstoolbarbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Generated by Internals Viewer
        ///DBCC TRACEON(3604)
        ///DBCC PAGE({0},{1},{2},{3})
        ///GO.
        /// </summary>
        internal static string SQL_CopyDbccPage {
            get {
                return ResourceManager.GetString("SQL_CopyDbccPage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WindowSplit {
            get {
                object obj = ResourceManager.GetObject("WindowSplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
