//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalsViewer.Internals.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InternalsViewer.Internals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT s.name+&apos;.&apos;+o.name AS Alloc_Unit
        ///FROM   sys.allocation_units au
        ///       INNER JOIN sys.partitions p ON au.container_id = p.partition_id
        ///       INNER JOIN sys.objects o ON p.object_id = o.object_id
        ///       INNER JOIN sys.schemas s ON s.schema_id = o.schema_id
        ///WHERE  au.allocation_unit_id = @allocation_unit_id.
        /// </summary>
        internal static string SQL_Allocation_Unit {
            get {
                return ResourceManager.GetString("SQL_Allocation_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT o.object_id
        ///	  ,s.name AS schema_name
        ///	  ,o.name AS table_name
        ///	  ,is_ms_shipped AS system 
        ///	  ,iau.first_iam_page
        ///                     ,p.index_id
        ///	  ,CASE iau.type
        ///			WHEN 1 THEN &apos;Row Data&apos;
        ///			WHEN 2 THEN &apos;LOB Data&apos;
        ///			WHEN 3 THEN &apos;Row Overflow Data&apos;
        ///	   END AS type_description
        ///	  ,iau.type
        ///FROM   sys.all_objects o
        ///	   INNER JOIN sys.schemas s ON o.schema_id = s.schema_id 
        ///	   INNER JOIN sys.partitions p ON p.object_id = o.object_id
        ///	   INNER JOIN sys.system_internals_allocation_unit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_Allocation_Units {
            get {
                return ResourceManager.GetString("SQL_Allocation_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKPOINT.
        /// </summary>
        internal static string SQL_Checkpoint {
            get {
                return ResourceManager.GetString("SQL_Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(data_compression, 0) FROM sys.partitions WHERE partition_id = @partition_id.
        /// </summary>
        internal static string SQL_Compression {
            get {
                return ResourceManager.GetString("SQL_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name FROM sys.databases WHERE database_id = @database_id.
        /// </summary>
        internal static string SQL_Database {
            get {
                return ResourceManager.GetString("SQL_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT o.object_id
        ///	  ,s.name AS schema_name
        ///	  ,o.name AS table_name
        ///	  ,is_ms_shipped AS system 
        ///FROM   sys.objects o 
        ///	   INNER JOIN sys.schemas s ON o.schema_id = s.schema_id 
        ///WHERE  type IN (&apos;U&apos;,&apos;S&apos;)
        ///ORDER BY is_ms_shipped desc, s.name asc , o.name asc.
        /// </summary>
        internal static string SQL_Database_Tables {
            get {
                return ResourceManager.GetString("SQL_Database_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT   d.database_id
        ///	    ,d.name
        ///        ,SUM(size) AS Size
        ///        ,d.state 
        ///	    ,COUNT(*) AS DataFiles
        ///       ,d.compatibility_level
        ///FROM     sys.databases d  
        ///	     INNER JOIN sys.master_files mf ON d.database_id = mf.database_id 
        ///WHERE    type = 0
        ///GROUP BY d.database_id
        ///		,d.name
        ///		,d.state 
        ///        ,compatibility_level   
        ///ORDER BY d.name.
        /// </summary>
        internal static string SQL_Databases {
            get {
                return ResourceManager.GetString("SQL_Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT first_page   
        ///      ,root_page
        ///      ,first_iam_page
        ///      ,partition_number
        ///FROM   sys.system_internals_allocation_units iau
        ///       INNER JOIN sys.partitions p ON iau.container_id = p.partition_id
        ///       INNER JOIN sys.indexes    i ON p.object_id = i.object_id
        ///                                      AND
        ///                                      i.index_id   = p.index_id
        ///WHERE p.object_id = OBJECT_ID(@ObjectName) AND ISNULL(i.name, &apos;&apos;) = @IndexName
        ///ORDER BY partition_number.
        /// </summary>
        internal static string SQL_EntryPoints {
            get {
                return ResourceManager.GetString("SQL_EntryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT size FROM sys.database_files WHERE file_id = @file_id.
        /// </summary>
        internal static string SQL_File_Size {
            get {
                return ResourceManager.GetString("SQL_File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE #FileStats
        ///            (file_id int
        ///            ,filegroup int  
        ///            ,total_extents int
        ///            ,used_extents int 
        ///            ,name sysname
        ///            ,file_name nchar(520))
        ///INSERT #FileStats EXEC (&apos;dbcc showfilestats&apos;)
        ///		
        ///SELECT df.file_id
        ///      ,df.type
        ///      ,fg.name as filegroup_name
        ///      ,df.name
        ///      ,physical_name
        ///      ,size
        ///      ,total_extents
        ///      ,used_extents
        ///FROM   sys.database_files df
        ///       INNER JOIN sys.filegroups fg ON df.data_space_id = fg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_Files {
            get {
                return ResourceManager.GetString("SQL_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(OBJECTPROPERTY(OBJECT_ID(@TableName), &apos;TableHasClustIndex&apos;), 0).
        /// </summary>
        internal static string SQL_ObjectHasClusteredIndex {
            get {
                return ResourceManager.GetString("SQL_ObjectHasClusteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBCC PAGE({0},{1},{2},{3}) WITH TABLERESULTS.
        /// </summary>
        internal static string SQL_Page {
            get {
                return ResourceManager.GetString("SQL_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(BIT, IS_SRVROLEMEMBER(&apos;sysadmin&apos;)).
        /// </summary>
        internal static string SQL_Sysadmin_Check {
            get {
                return ResourceManager.GetString("SQL_Sysadmin_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT o.object_id
        ///      ,s.name AS schema_name
        ///      ,CASE WHEN i.name IS NULL 
        ///            THEN o.name
        ///            ELSE o.name + &apos;.&apos; + i.name 
        ///       END AS object_name
        ///      ,o.type AS object_type
        ///      ,i.type_desc
        ///      ,i.type AS index_type
        ///      ,i.index_id AS index_id
        ///      ,iau.first_iam_page
        ///      ,iau.root_page
        ///      ,iau.first_page
        ///      ,iau.total_pages
        ///      ,iau.used_pages
        ///      ,iau.data_pages
        ///      ,iau.type AS alloc_unit_type
        ///      ,iau.type_desc
        ///      ,partition_number
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_Table_Info {
            get {
                return ResourceManager.GetString("SQL_Table_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Current LSN] AS LSN
        ///      ,REPLACE(SUBSTRING(Operation, 5, LEN(Operation)),&apos;_&apos;,&apos; &apos;) AS Operation
        ///      ,CASE WHEN Context = &apos;LCX_NULL&apos; THEN NULL
        ///      ELSE REPLACE(SUBSTRING(Context, 5, LEN(Context)),&apos;_&apos;,&apos; &apos;) 
        ///      END AS Context
        ///      ,AllocUnitId
        ///      ,AllocUnitName
        ///      ,[Page ID] AS PageId
        ///      ,[Slot ID] AS SlotId
        ///      ,RowFlags
        ///      ,[Num Elements] AS NumElements
        ///      ,[Offset in Row] AS OffsetInRow
        ///      ,[Rowbits First Bit] AS RowbitsFirstBit
        ///      ,[Rowbits Bit Count] AS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_TransactionLog {
            get {
                return ResourceManager.GetString("SQL_TransactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SERVERPROPERTY(&apos;productversion&apos;), size FROM sys.database_files WHERE file_id = 1.
        /// </summary>
        internal static string SQL_Version {
            get {
                return ResourceManager.GetString("SQL_Version", resourceCulture);
            }
        }
    }
}
