namespace InternalsViewer.Internals.Annotations;

public enum ItemType
{
    // Allocations
    PageAddress,

    // Page Header
    AllocationUnitId,
    HeaderPageAddress,
    PageType,
    NextPage,
    PreviousPage,
    InternalObjectId,
    InternalIndexId,
    IndexLevel,
    SlotCount,
    FixedLengthSize,
    FreeCount,
    FreeDataOffset,
    ReservedCount,
    TransactionReserved,
    TornBits,
    FlagBits,
    Lsn,
    HeaderVersion,
    GhostRecordCount,
    TypeFlagBits,
    InternalTransactionId,

    // FixedVar Format
    StatusBitsA,
    StatusBitsB,
    ColumnCountOffset,
    ColumnCount,
    NullBitmap,
    VariableLengthColumnCount,
    VariableLengthColumnOffsetArray,
    FixedLengthValue,
    VariableLengthValue,
    ForwardingStub,

    // CD Format
    RecordHeader,
    ColumnDescriptor,
    ColumnDescriptors,
    ShortDataClusterArray,
    ShortFieldValue,
    LongDataHeader,
    LongDataOffsetCount,
    LongDataOffsetArray,
    LongDataClusterArray,
    LongFieldValue,

    // Index
    UniquifierIndex,
    Rid,
    DownPagePointer,

    // Compression Info
    Header,
    PageModificationCount,
    Length,
    Size,
    AnchorRecord,
    CompressionDictionary,

    // Dictionary
    DictionaryColumnOffsets,
    DictionaryEntryCount,
    DictionaryValue,
    VariableLengthDataHeader,
    VariableLengthDataSubLobType,
    VariableLengthDataValueCount,
    VariableLengthDataMaxStringSize,
    PageSizeArray,
    PageSizeArraySubLobType,
    PageSizeArrayElementSize,
    PageSizeArrayElementCount,
    PageSizeArrayData,
    ValuePageSubLobType,
    ValuePageFlags,
    ValuePageReserved,
    ValuePageValueSize,
    ValuePageValueCount,
    ValuePagePayloadSize,
    ValuePagePayload,
    SegmentRowSource,
    DictionaryEntries,
    DictionarySymbol,

    // Blob
    BlobId,
    BlobData,
    BlobLength,
    BlobType,
    BlobSize,
    BlobChildLength,
    BlobChildOffset,
    Level,
    Timestamp,
    PointerType,

    CurrentLinks,
    MaxLinks,

    // Sparse Header
    ComplexHeader,
    SparseColumnCount,
    SparseColumnOffsets,
    SparseColumns,

    // Overflow
    OverflowLevel,
    OverflowLength,
    Unused,
    UpdateSeq,

    // BootPage
    CurrentVersion,
    CreatedVersion,
    DatabaseId,
    DatabaseNameLength,
    DatabaseName,
    CreatedDateTime,
    ModifiedDateTime,
    CompatabilityLevel,
    MaxLogSpaceUsed,
    MaxDatabaseTimestamp,
    Status,
    ReleaseStatus,
    LastTransactionId,
    DbccFlags,
    NextAllocationUnitId,
    Collation,
    ResourceDatabaseVersion,
    ServiceBrokerOptions,
    PersistentVersionStoreRowsetId,
    PersistentVersionStoreLongTermRowsetId,
    FamilyGuid,
    RecoveryForkGuid,
    ServiceBrokerGuid,
    FirstAllocationUnitsPage,
    CheckpointLsn,
    DirtyPageLsn,
    LatestVersioningUpgradeLsn,

    // Columnstore
    SegmentVersion,
    SegmentLobType,
    SegmentStructureType,
    SegmentReserved,
    SegmentUnknown,
    BookmarkCount,
    BookmarkDistance,
    BookmarkPosition,
    BookmarkEndRow,
    RleArrayCount,
    RleEntrySize,
    RleValue,
    RleCount,
    RleBitpackIndex,
    BitpackEntrySize,
    BitpackUnitCount,
    BitpackMinId,
    BitpackUnit,
    BitpackValue,
    StringHandleOffset,
    StringHandlePage,
    StringPageSize,
    StringEntryLength,
    StringEntryValue,
    StringEntryCode,
    StringPageSubLobType,
    StringPageFlags,
    StringPageStringCount,
    StringPageFreeSpace,
    StringPageFreeSpaceOffset,
    StringPageUncompressedSize,
    StringPageAlignment,
    HuffmanBlobType,
    HuffmanBitCount,
    HuffmanDecoderBitSize,
    HuffmanCompressedSize,
    HuffmanCharacterSet,
    HuffmanCodeLengths,
    DictionaryVersion,
    DictionaryLobType,
    DictionaryStringCount,
    DictionarySubLobType,
    DictionaryReserved,
    DictionaryUnknown,
    DictionaryMaxStringSize,
    DictionaryHandleSize,
    DictionaryHandleCount,
    DictionaryPageCount,
    BookmarkEntry,
    RleEntry,
    DictionaryHandle,
    DictionaryHandleOffset,
    DictionaryHandlePage,
    DictionaryPageSize,
    DictionaryStringStore,
    DictionaryHandleArray,
    DictionaryPageSizeArray,
    DictionaryElementCount,
    DictionaryHashTable,
    DictionaryValueArray,
    DictionaryBucketSize,
    DictionaryBucketCount,
    DictionaryMaxLocalEntryCount,
    DictionaryHashEntrySize,
    DictionaryHashEntryCount,
    DictionaryCollisionCount,
    DictionaryBucketIndexMask,
    DictionaryElementSize,
    DictionaryValueCount,

    // File Header Page
    LogicalName,
    BindingId,
    FileIdGuid,
    FileId,
    FileGroupId,
    FileSize,
    MaxSize,
    MinSize,
    UserShrinkSize,
    Growth,
    Perf,
    FileStatus,
    SectorSize,
    BackupLsn,
    FirstUpdateLsn,
    OldestRestoredLsn,
    MaxLsn,
    FirstLsn,
    CreateLsn,
    DifferentialBaseLsn,
    DifferentialBaseGuid,
    FileOfflineLsn,
    RestoreStatus,
    RestoreRedoStartLsn
}
