namespace InternalsViewer.Query.TransactionLog;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo
public enum LogOperation
{
    LOP_NULL = 0,
    LOP_FORMAT_PAGE = 1,
    LOP_INSERT_ROWS = 2,
    LOP_DELETE_ROWS = 3,
    LOP_MODIFY_ROW = 4,
    LOP_MODIFY_HEADER = 5,
    LOP_MODIFY_COLUMNS = 6,
    LOP_SET_BITS = 7,
    LOP_SET_FREE_SPACE = 10,
    LOP_DELETE_SPLIT = 11,
    LOP_UNDO_DELETE_SPLIT = 12,
    LOP_EXPUNGE_ROWS = 13,
    LOP_FILE_HDR_MODIFY = 16,
    LOP_CLEAR_GAM_BITS = 17,
    LOP_COUNT_DELTA = 18,
    LOP_ROOT_CHANGE = 19,
    LOP_COMPRESSION_INFO = 20,
    LOP_ENCRYPT_PAGE = 21,
    LOP_INSYSXACT = 22,
    LOP_BEGIN_XACT = 128,
    LOP_COMMIT_XACT = 129,
    LOP_ABORT_XACT = 130,
    LOP_PREP_XACT = 131,
    LOP_MARK_SAVEPOINT = 132,
    LOP_FORGET_XACT = 133,

    LOP_CREATE_FILE = 134,
    LOP_DROP_FILE = 135,
    LOP_FILE_OP = 136,
    LOP_HOBT_DDL = 137,
    LOP_IDENT_NEWVAL = 138,
    LOP_IDENT_SENTVAL = 139,
    LOP_HOBT_DELTA = 140,
    LOP_LOCK_XACT = 141,
    LOP_CREATE_STREAMFILE = 142,
    LOP_MIGRATE_LOCKS = 143,
    LOP_DROP_STREAMFILE = 144,
    LOP_FS_DOWNLEVEL_OP = 145,
    LOP_MODIFY_STREAMFILE_HDR = 146,
    LOP_FS_CONTAINER_SIZE_DELTA = 147,
    LOP_BP_DBVER = 148,
    LOP_COPY_VERSION_INFO = 149,
    LOP_BEGIN_CKPT = 150,
    LOP_XACT_CKPT = 152,
    LOP_END_CKPT = 153,
    LOP_BUF_WRITE = 154,

    LOP_BEGIN_RECOVERY = 160,
    LOP_END_RECOVERY = 161,
    LOP_TENANT_LOG = 162,

    LOP_CREATE_INDEX = 173,
    LOP_DROP_INDEX = 174,
    LOP_CREATE_ALLOCCHAIN = 176,
    LOP_CREATE_FTCAT = 180,
    LOP_DROP_FTCAT = 181,

    LOP_RECONFIGURE = 124,
    LOP_STRIP_VERSION_INFO = 125,
    LOP_RESET_VERSION_INFO = 126,
    LOP_MAX_PAGE_OP = 127,

    LOP_REVERT_ROW = 123,

    LOP_RANGE_INSERT = 220,
    LOP_INVALIDATE_CACHE = 221,
    LOP_CSI_ROWGROUP = 223,
    LOP_CSI_DELETE_BUFFER = 224,
    LOP_CSI_DBMP_INVALIDATION = 225,

    LOP_SLOG_CKPT = 242,
    LOP_PREPARE_REMOTE_FILE = 243,
    LOP_CTR_NEST_ABORT = 244,
    LOP_EE = 245,

    LOP_SEREPL_MSG = 240,
    LOP_AUDIT = 241,

    LOP_FILESTREAM_INFO_BEGIN = 212,
    LOP_FILESTREAM_INFO_END = 213,

    LOP_TEXT_INFO_BEGIN = 204,
    LOP_TEXT_INFO_END = 205,
    LOP_TEXT_POINTER = 203,
    LOP_TEXT_VALUE = 207,

    LOP_REPL_COMMAND = 200,
    LOP_REPL_NOOP = 206,

    LOP_PAGE_REENCRYPT = 216,
    LOP_BULK_EXT_ALLOCATION = 214,
    LOP_SECURITY_OP = 215,

    LOP_SHRINK_NOOP = 211,
    LOP_MAX_REPL_OP = 210,

    LOP_HK = 230,
    LOP_HK_CHAINED = 232,
    LOP_HK_CHECKPOINT = 231,
    LOP_HK_DEPLOYED = 233,
    LOP_HK_UNDEPLOYED = 234
}