using InternalsViewer.Internals.Engine.Address;

namespace InternalsViewer.TransactionLog.LogRecords;

public record LogRecord
{
    /// <summary>
    /// Log Sequence Number (LSN) unique identifier
    /// </summary>
    /// <remarks>
    /// Composed of:
    ///     - VLF (Virtual Log File) sequence number
    ///     - log block offset - record sequence within the block
    /// </remarks>
    public required LogSequenceNumber Lsn { get; init; }

    /// <summary>
    /// LSN of the previous log record generated by the same transaction
    /// </summary>
    /// <remarks>
    /// Stored at offset 4 of the record header (10 bytes).
    ///
    /// Forms the backwards chain rollback walks to undo a transaction - each record points at the transaction's previous record,
    /// terminating at zero on the LOP_BEGIN_XACT record.
    ///
    /// Zero for records outside a transaction.
    /// </remarks>
    public required LogSequenceNumber PreviousLsn { get; init; }

    /// <summary>
    /// Transaction Id
    /// </summary>
    /// <remarks>
    /// Formatted as high:low hex, e.g. 0000:0000443e.
    ///
    /// Stored at offset 16 of the record header as a 6 byte XDESID (4 byte low part followed by 2 byte high part).
    ///
    /// 0000:00000000 for non-transactional records such as PFS updates and checkpoints.
    /// </remarks>
    public string LogTransactionId { get; set; } = string.Empty;

    /// <summary>
    /// Log operation type
    /// </summary>
    /// <remarks>
    /// Single byte at offset 22 of the record header.
    /// 
    /// Determines the layout of the record body after the common 24 byte header, and therefore which LogRecord subtype the record parses
    /// to.
    /// </remarks>
    public LogOperation Operation { get; set; }

    /// <summary>
    /// Log operation context
    /// </summary>
    /// <remarks>
    /// Single byte at offset 23 of the record header
    /// </remarks>
    public LogContext Context { get; set; }

    /// <summary>
    /// Transaction id (XDESID) as a 64 bit value
    /// </summary>
    /// <remarks>
    /// The 6 byte XDESID at offset 16 as (high 16 bits >> 32) | low 32 bits
    /// 
    /// Zero for non-transactional records.
    /// </remarks>
    public long? TransactionId { get; set; }

    /// <summary>
    /// Sequence number assigned when correlating log records with query events
    /// </summary>
    /// <remarks>
    /// Not part of the on-disk record - populated by consumers to order records alongside captured events.
    /// </remarks>
    public int? SequenceId { get; set; }

    /// <summary>
    /// Size in bytes of the fixed length portion of the record
    /// </summary>
    /// <remarks>
    /// Read from the 2 byte field at offset 2 of the record header and includes the 24 byte common header.
    ///
    /// The variable length element section starts at this offset
    /// </remarks>
    public short LogRecordSize { get; set; }

    public virtual string Description { get; } = "Log Record";
}
