using InternalsViewer.Internals.Engine.Address;

namespace InternalsViewer.Query.TransactionLog.LogRecords;

public record LogRecord
{
    /// <summary>
    /// Log Sequence Number uniquely identifying this log record
    /// </summary>
    /// <remarks>
    /// Composed of VLF sequence number : log block offset : record sequence within the block. The LSN is not stored in
    /// the record itself - it is derived from the record's position in the log, so the reader supplies it alongside
    /// the raw record bytes (fn_dblog exposes it as [Current LSN]).
    /// </remarks>
    public required LogSequenceNumber Lsn { get; init; }

    /// <summary>
    /// LSN of the previous log record generated by the same transaction
    /// </summary>
    /// <remarks>
    /// Stored at offset 4 of the record header (10 bytes). Forms the backwards chain rollback walks to undo a
    /// transaction - each record points at the transaction's previous record, terminating at zero on the
    /// LOP_BEGIN_XACT record. Zero for records outside a transaction.
    /// </remarks>
    public required LogSequenceNumber PreviousLsn { get; init; }

    /// <summary>
    /// Transaction id in the fn_dblog [Transaction ID] display format
    /// </summary>
    /// <remarks>
    /// Formatted as high:low hex, e.g. 0000:0000443e. Stored at offset 16 of the record header as a 6 byte XDESID
    /// (4 byte low part followed by 2 byte high part). 0000:00000000 for non-transactional records such as PFS
    /// updates and checkpoints.
    /// </remarks>
    public string LogTransactionId { get; set; } = string.Empty;

    /// <summary>
    /// Operation the log record performs
    /// </summary>
    /// <remarks>
    /// Single byte at offset 22 of the record header.
    /// Determines the layout of the record body after the common 24 byte header, and therefore which LogRecord subtype the record parses
    /// to.
    /// </remarks>
    public LogOperation Operation { get; set; }

    /// <summary>
    /// Context describing the type of object or page the operation applies to
    /// </summary>
    /// <remarks>
    /// Single byte at offset 23 of the record header. The same operation is reused across contexts, e.g. LOP_SET_BITS occurs with GAM,
    /// SGAM, IAM, DIFF_MAP and PFS contexts depending on which allocation page is
    /// being updated.
    /// </remarks>
    public LogContext Context { get; set; }

    /// <summary>
    /// Transaction id (XDESID) combined into a single 64 bit value
    /// </summary>
    /// <remarks>
    /// The 6 byte XDESID at offset 16 as (high 16 bits &lt;&lt; 32) | low 32 bits - the same value as LogTransactionId in numeric form.
    /// Zero for non-transactional records.
    /// </remarks>
    public long? TransactionId { get; set; }

    /// <summary>
    /// Sequence number assigned when correlating log records with query events
    /// </summary>
    /// <remarks>
    /// Not part of the on-disk record - populated by consumers to order records alongside captured events.
    /// </remarks>
    public int? SequenceId { get; set; }

    /// <summary>
    /// Size in bytes of the fixed length portion of the record
    /// </summary>
    /// <remarks>
    /// Read from the 2 byte field at offset 2 of the record header and includes the 24 byte common header. The variable length element
    /// section starts at this offset. Matches the fn_dblog [Log Record Fixed Length] column and is used as part of the key when matching
    /// records to transaction_log XEvents.
    /// </remarks>
    public short LogRecordSize { get; set; }

    public virtual string Description { get; } = "Log Record";
}
