using Microsoft.CodeAnalysis;

namespace InternalsViewer.Internals.Metadata.SourceGenerators;

[Generator]
public class AttributeGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(i =>
        {
            var attributeSource = @"// <auto-generated />
#nullable enable

using System;
using System.Data;
using System.Diagnostics.CodeAnalysis;

namespace InternalsViewer.Internals.Generators;

[ExcludeFromCodeCoverage]
[AttributeUsage(AttributeTargets.Class)]
public class InternalsMetadataAttribute : Attribute;

[ExcludeFromCodeCoverage]
[AttributeUsage(AttributeTargets.Property)]
public class InternalsMetadataColumnAttribute(string Name, int ColumnId, SqlDbType DataType, int DataLength, short LeafOffset, short NullBit) 
    : Attribute;
";

            i.AddSource("InternalsMetadataAttribute.g.cs", attributeSource);
        });
    }
}
