name: Build MSI installer

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\DevEnv.com
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: latest
        

      
    - name: Build MSI
      run: |
        "%MSBUILD_PATH% "InternalsViewer.UI.App.Installer\InternalsViewer.UI.App.Installer.vdproj" /rebuild "Release|x64"
