name: Build MSI installer

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        default: '1.0.0'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\DevEnv.com
      PROJECT_PATH: InternalsViewer.sln
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: latest
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Build MSI
      shell: cmd
      run: |
        "%MSBUILD_PATH%" "%PROJECT_PATH%" /build Installer

    - uses: actions/upload-artifact@v4
      with:
        name: internals-viewer-msi.1.0.${{ github.run_id }}
        if-no-files-found: error
        path: src\InternalsViewer.UI.App.Installer\Installer\InternalsViewer.msi'
