name: Build Internals Viewer App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish
      run: dotnet publish InternalsViewer.UI.App -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false

    - uses: actions/upload-artifact@v4
      with:
        name: internals-viewer-app=1.0.${{ github.run_id }}
        if-no-files-found: error
        path: src/InternalsViewer.UI.App/bin/windows/Release/net8.0-windows/win-x64/publish/
