name: Build application and create GitHub release
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    uses: ./.github/workflows/build-msix-sideload.yml
    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Create release
        run: |
          gh release create ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
